import * as fs from 'fs'; import * as os from 'os'; import * as path from 'path';
import { afterEach, describe, expect, it, vi } from 'vitest';
import { RelationshipMemoryOwnerControlPlane, RelationshipMemoryRuntime, RelationshipMemoryStore, rebuildProjection } from '../src/index.js';
const dirs:string[]=[]; const temp=()=>{const d=fs.mkdtempSync(path.join(os.tmpdir(),'rm-owner-'));dirs.push(d);return d};
afterEach(()=>{while(dirs.length)fs.rmSync(dirs.pop()!,{recursive:true,force:true})});
const message={conversation_id:'c',message_id:'m1',role:'user' as const,quote:'original exact quote',captured_at:'2026-01-01T00:00:00Z'};
function fixture(){const dir=temp(); const store=new RelationshipMemoryStore(dir,'s'); const rt=new RelationshipMemoryRuntime(store,new Map([[message.message_id,message]]),()=> '2026-01-02T00:00:00Z'); store.beginBatch('b','2026-01-01T00:00:00Z'); const r=rt.remember('b',{schema_version:1,kind:'personal_experience',summary:'old summary',participants:['user'],evidence_message_ids:['m1'],payload:{title:'Old',experience:'old payload'}}); return {dir,store,rt,id:r.memory_id!};}

describe('owner control plane',()=>{
 it('keeps genesis/evidence immutable while revising effective semantics and replaying idempotently',()=>{const {dir,store,id}=fixture(); const memBefore=fs.readFileSync(path.join(dir,'memories.jsonl'),'utf8'); const evBefore=fs.readFileSync(path.join(dir,'evidence.jsonl'),'utf8'); const owner=new RelationshipMemoryOwnerControlPlane(store,()=> '2026-01-03T00:00:00Z'); const cmd={revision_id:'r1',kind:'relationship_event' as const,summary:'corrected meaning',participants:['user'] as const,payload:{event:'Correction',meaning:'correct payload'}}; owner.revise(id,cmd as any); owner.revise(id,cmd as any); expect(fs.readFileSync(path.join(dir,'memories.jsonl'),'utf8')).toBe(memBefore); expect(fs.readFileSync(path.join(dir,'evidence.jsonl'),'utf8')).toBe(evBefore); expect(store.listEvidence()[0].quote).toBe(message.quote); expect(store.listOwnerRevisions()).toHaveLength(1); expect(owner.getEffective(id)).toEqual(expect.objectContaining({kind:'relationship_event',summary:'corrected meaning',payload:{event:'Correction',meaning:'correct payload'},status:'active',owner_corrected:true,latest_revision_id:'r1'}));});
 it('rejects invalid/forbidden revisions without append',()=>{const {store,id}=fixture(); const owner=new RelationshipMemoryOwnerControlPlane(store); expect(()=>owner.revise(id,{revision_id:'bad',kind:'inside_joke',summary:'bad',participants:['user'],payload:{name:'x',meaning:'y'}} as any)).toThrow(); expect(()=>owner.revise(id,{revision_id:'bad2',kind:'personal_experience',summary:'bad',participants:['user'],payload:{title:'x',experience:'y'},memory_id:'forged'} as any)).toThrow(/authoritative/); expect(store.listOwnerRevisions()).toHaveLength(0);});
 it('materializes canonical owner inputs once for effective-list reads',()=>{const {store,id}=fixture(); const owner=new RelationshipMemoryOwnerControlPlane(store,()=> '2026-01-03T00:00:00Z'); owner.revise(id,{revision_id:'r1',kind:'personal_experience',summary:'materialized',participants:['user'],payload:{title:'New',experience:'new payload'}}); const listMemories=vi.spyOn(store,'listMemories'); const listOwnerRevisions=vi.spyOn(store,'listOwnerRevisions'); expect(owner.listEffective()).toEqual([expect.objectContaining({memory_id:id,summary:'materialized',latest_revision_id:'r1'})]); expect(listMemories).toHaveBeenCalledTimes(1); expect(listOwnerRevisions).toHaveBeenCalledTimes(1);});
 it('deactivate hides effective search/projection and restore revives latest revision across reconstruction',()=>{const {dir,store,rt,id}=fixture(); const evidenceBefore=fs.readFileSync(path.join(dir,'evidence.jsonl'),'utf8'); const owner=new RelationshipMemoryOwnerControlPlane(store,()=> '2026-01-03T00:00:00Z'); owner.revise(id,{revision_id:'r1',kind:'personal_experience',summary:'new searchable phrase',participants:['user'],payload:{title:'New',experience:'new payload'}}); const p1=rebuildProjection(store); expect(rt.memorySearch({query:'new searchable phrase'})).toHaveLength(1); owner.deactivate(id,{revision_id:'r2'}); const p2=rebuildProjection(store); expect(p2.revision).not.toBe(p1.revision); expect(p2.blocks.remembered_experiences).not.toContain(id); expect(rt.memorySearch({query:'new searchable phrase'})).toHaveLength(0); expect(owner.search({active:false,memory_id:id})).toHaveLength(1); owner.restore(id,{revision_id:'r3'}); expect(fs.readFileSync(path.join(dir,'evidence.jsonl'),'utf8')).toBe(evidenceBefore); expect(store.listEvidence().find(e=>e.message_id===message.message_id)?.quote).toBe(message.quote); expect(owner.getEffective(id)?.payload).toEqual({title:'New',experience:'new payload'}); const p3=rebuildProjection(store); expect(p3.revision).not.toBe(p2.revision); expect(p3.blocks.remembered_experiences).toContain('new searchable phrase'); expect(rt.memorySearch({query:'new searchable phrase'})).toHaveLength(1); const rebuilt=new RelationshipMemoryOwnerControlPlane(new RelationshipMemoryStore(dir,'s')); expect(rebuilt.getEffective(id)).toEqual(owner.getEffective(id)); expect(rebuilt.history(id).map(r=>r.revision_id)).toEqual(['r1','r2','r3']); expect(rebuilt.getGenesis(id)?.summary).toBe('old summary');});
});
